global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'app-backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['app-backend:3002']
      
  - job_name: 'app-orchestrator'
    scrape_interval: 5s
    static_configs:
      - targets: ['app-orchestrator:3003']

# remote_write:
#   - url: '<Your Prometheus remote_write endpoint>'
#     basic_auth:
#       username: '<Your Grafana Username>'
#       password: '<Your Grafana API key>'